CREATE TABLE IF NOT EXISTS admin_accounts (
    admin_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    last_login_at TIMESTAMP,
    PRIMARY KEY (admin_id),
    CONSTRAINT uk_admin_accounts_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS admin_refresh_tokens (
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    admin_id BIGINT NOT NULL,
    refresh_token VARCHAR(512) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    PRIMARY KEY (token_id),
    CONSTRAINT uk_admin_refresh_token UNIQUE (refresh_token),
    CONSTRAINT fk_admin_refresh_token_account FOREIGN KEY (admin_id) REFERENCES admin_accounts(admin_id)
);

CREATE INDEX IF NOT EXISTS idx_admin_refresh_token_admin ON admin_refresh_tokens(admin_id);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    admin_id BIGINT NOT NULL,
    action_type VARCHAR(80) NOT NULL,
    target_type VARCHAR(80) NOT NULL,
    target_id BIGINT,
    before_value TEXT,
    after_value TEXT,
    reason TEXT,
    ip_address VARCHAR(255),
    PRIMARY KEY (audit_id)
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_admin ON admin_audit_logs(admin_id, created_at);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_target ON admin_audit_logs(target_type, target_id, created_at);

CREATE TABLE IF NOT EXISTS user_account_restrictions (
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    reason TEXT,
    updated_by_admin_id BIGINT,
    PRIMARY KEY (user_id),
    CONSTRAINT fk_user_account_restrictions_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);
