CREATE TABLE IF NOT EXISTS admin_account_roles (
    admin_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (admin_id, role),
    CONSTRAINT fk_admin_account_roles_account FOREIGN KEY (admin_id) REFERENCES admin_accounts(admin_id) ON DELETE CASCADE
);

INSERT INTO admin_account_roles (admin_id, role)
SELECT admin_id, role
FROM admin_accounts
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS user_inquiries (
    inquiry_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    related_chat_room_id BIGINT,
    related_meeting_id BIGINT,
    related_payment_id VARCHAR(120),
    answer TEXT,
    answered_by_admin_id BIGINT,
    answered_at TIMESTAMP,
    PRIMARY KEY (inquiry_id),
    CONSTRAINT fk_user_inquiries_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE INDEX IF NOT EXISTS idx_user_inquiries_status ON user_inquiries(status, created_at);
CREATE INDEX IF NOT EXISTS idx_user_inquiries_user ON user_inquiries(user_id, created_at);
