-- public.device_token definition

-- Drop table

-- DROP TABLE public.device_token;

CREATE TABLE public.device_token (
                                     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     active bool NOT NULL,
                                     last_seen_at timestamptz(6) NULL,
                                     "token" varchar(255) NOT NULL,
                                     user_id int8 NULL,
                                     CONSTRAINT device_token_pkey PRIMARY KEY (id),
                                     CONSTRAINT idx_device_token_token UNIQUE (token)
);
CREATE INDEX idx_device_token_active ON public.device_token USING btree (active);
CREATE INDEX idx_device_token_user ON public.device_token USING btree (user_id);


-- public.love_view_recommend_history definition

-- Drop table

-- DROP TABLE public.love_view_recommend_history;

CREATE TABLE public.love_view_recommend_history (
                                                    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                    recommend_type varchar(255) NOT NULL,
                                                    recommended_at timestamp(6) NOT NULL,
                                                    requester_user_id int8 NOT NULL,
                                                    target_user_id int8 NOT NULL,
                                                    CONSTRAINT love_view_recommend_history_pkey PRIMARY KEY (id),
                                                    CONSTRAINT love_view_recommend_history_recommend_type_check CHECK (((recommend_type)::text = ANY ((ARRAY['FREE'::character varying, 'EXTRA_VIP'::character varying, 'EXTRA_MEMBERSHIP'::character varying, 'EXTRA_TING'::character varying])::text[])))
);
CREATE INDEX idx_req_target_time ON public.love_view_recommend_history USING btree (requester_user_id, target_user_id, recommended_at);
CREATE INDEX idx_req_time ON public.love_view_recommend_history USING btree (requester_user_id, recommended_at);


-- public.policy_config definition

-- Drop table

-- DROP TABLE public.policy_config;

CREATE TABLE public.policy_config (
                                      id int8 NOT NULL,
                                      benefit_basic_daily_love_view int4 NULL,
                                      benefit_basic_daily_profile int4 NULL,
                                      benefit_membership_cycle_extra_profiles int4 NULL,
                                      benefit_membership_cycle_free_likes int4 NULL,
                                      benefit_membership_cycle_free_messages int4 NULL,
                                      benefit_vip_daily_extra_profiles int4 NULL,
                                      benefit_vip_daily_free_likes int4 NULL,
                                      benefit_vip_daily_free_messages int4 NULL,
                                      match_candidate_pool_size int4 NULL,
                                      match_cooldown_hours int4 NULL,
                                      match_pick_pool_size int4 NULL,
                                      ting_cost_extra_profile int4 NULL,
                                      ting_cost_extra_profile_bundle5 int4 NULL,
                                      ting_cost_like int4 NULL,
                                      ting_cost_message int4 NULL,
                                      ting_cost_view_extra_photo int4 NULL,
                                      ting_cost_view_high_score_profile int4 NULL,
                                      ting_cost_view_liked_me_profile int4 NULL,
                                      ting_cost_view_score int4 NULL,
                                      ting_vip_threshold int4 NULL,
                                      updated_at timestamp(6) NOT NULL,
                                      "version" int8 NULL,
                                      CONSTRAINT policy_config_pkey PRIMARY KEY (id)
);


-- public.profile_recommend_history definition

-- Drop table

-- DROP TABLE public.profile_recommend_history;

CREATE TABLE public.profile_recommend_history (
                                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                  recommend_type varchar(255) NOT NULL,
                                                  recommended_at timestamp(6) NOT NULL,
                                                  requester_user_id int8 NOT NULL,
                                                  target_user_id int8 NOT NULL,
                                                  CONSTRAINT profile_recommend_history_pkey PRIMARY KEY (id),
                                                  CONSTRAINT profile_recommend_history_recommend_type_check CHECK (((recommend_type)::text = ANY ((ARRAY['FREE'::character varying, 'EXTRA_VIP'::character varying, 'EXTRA_MEMBERSHIP'::character varying, 'EXTRA_TING'::character varying])::text[])))
);


-- public.questions definition

-- Drop table

-- DROP TABLE public.questions;

CREATE TABLE public.questions (
                                  question_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  created_at timestamp(6) NOT NULL,
                                  updated_at timestamp(6) NOT NULL,
                                  question text NOT NULL,
                                  question_type varchar(255) NOT NULL,
                                  CONSTRAINT questions_pkey PRIMARY KEY (question_id),
                                  CONSTRAINT questions_question_type_check CHECK (((question_type)::text = ANY ((ARRAY['REQUIRED_TEXT'::character varying, 'REQUIRED_CHOICE'::character varying, 'OPTIONAL_TEXT'::character varying])::text[])))
);


-- public.ting_wallet definition

-- Drop table

-- DROP TABLE public.ting_wallet;

CREATE TABLE public.ting_wallet (
                                    user_id int8 NOT NULL,
                                    daily_love_view_granted_date date NULL,
                                    daily_love_view_remaining int4 NOT NULL,
                                    daily_profile_granted_date date NULL,
                                    daily_profile_remaining int4 NOT NULL,
                                    event_ting int4 NOT NULL,
                                    extra_profiles_by_ting_remaining int4 NOT NULL,
                                    m_active_until timestamp(6) NULL,
                                    m_cycle_start_at timestamp(6) NULL,
                                    m_monthly_extra_profiles_remaining int4 NOT NULL,
                                    m_monthly_free_likes_remaining int4 NOT NULL,
                                    m_monthly_extra_messages_remaining int4 NOT NULL,
                                    ting int4 NOT NULL,
                                    "version" int8 NULL,
                                    vip_daily_extra_profiles_remaining int4 NOT NULL,
                                    vip_daily_free_likes_remaining int4 NOT NULL,
                                    vip_daily_free_messages_remaining int4 NOT NULL,
                                    vip_granted_date date NULL,
                                    CONSTRAINT ting_wallet_pkey PRIMARY KEY (user_id)
);


-- public.university definition

-- Drop table

-- DROP TABLE public.university;

CREATE TABLE public.university (
                                   university_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   created_at timestamp(6) NOT NULL,
                                   updated_at timestamp(6) NOT NULL,
                                   "domain" varchar(255) NOT NULL,
                                   "name" varchar(255) NOT NULL,
                                   CONSTRAINT ukl0v23mm0y4u53a26k7malrfu1 UNIQUE (domain),
                                   CONSTRAINT university_pkey PRIMARY KEY (university_id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              user_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              created_at timestamp(6) NOT NULL,
                              updated_at timestamp(6) NOT NULL,
                              is_membership bool NOT NULL,
                              is_verified bool NOT NULL,
                              kakao_id varchar(255) NOT NULL,
                              phone_num varchar(255) NULL,
                              user_name varchar(255) NULL,
                              CONSTRAINT ukk4ycaj27putgcujmehwbsrmmc UNIQUE (kakao_id),
                              CONSTRAINT users_pkey PRIMARY KEY (user_id)
);


-- public.profile definition

-- Drop table

-- DROP TABLE public.profile;

CREATE TABLE public.profile (
                                profile_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                created_at timestamp(6) NOT NULL,
                                updated_at timestamp(6) NOT NULL,
                                alcohol varchar(255) NULL,
                                birth_date date NULL,
                                body_type varchar(255) NULL,
                                email varchar(255) NULL,
                                gender varchar(255) NOT NULL,
                                grade float8 NULL,
                                height int4 NULL,
                                mbti varchar(4) NULL,
                                nick_name varchar(255) NULL,
                                region_sido varchar(255) NULL,
                                region_sigungu varchar(255) NULL,
                                smoking varchar(255) NULL,
                                university varchar(255) NULL,
                                user_id int8 NOT NULL,
                                CONSTRAINT profile_alcohol_check CHECK (((alcohol)::text = ANY ((ARRAY['NON_DRINKER'::character varying, 'OCCASIONAL_DRINKER'::character varying, 'FREQUENT_DRINKER'::character varying])::text[]))),
	CONSTRAINT profile_body_type_check CHECK (((body_type)::text = ANY ((ARRAY['SLIM'::character varying, 'AVERAGE'::character varying, 'CHUBBY'::character varying])::text[]))),
	CONSTRAINT profile_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying])::text[]))),
	CONSTRAINT profile_pkey PRIMARY KEY (profile_id),
	CONSTRAINT profile_smoking_check CHECK (((smoking)::text = ANY ((ARRAY['NON_SMOKER'::character varying, 'VAPE_ONLY'::character varying, 'REGULAR_SMOKER'::character varying])::text[]))),
	CONSTRAINT ukc1dkiawnlj6uoe6fnlwd6j83j UNIQUE (user_id),
	CONSTRAINT ukcs9f0fwxtv6241hk3b82qyyyh UNIQUE (nick_name),
	CONSTRAINT fks14jvsf9tqrcnly0afsv0ngwv FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);


-- public.profile_image definition

-- Drop table

-- DROP TABLE public.profile_image;

CREATE TABLE public.profile_image (
                                      image_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      created_at timestamp(6) NOT NULL,
                                      updated_at timestamp(6) NOT NULL,
                                      file_name varchar(255) NOT NULL,
                                      image_index int4 NOT NULL,
                                      is_main bool NOT NULL,
                                      original_name varchar(255) NULL,
                                      url varchar(255) NOT NULL,
                                      profile_id int8 NOT NULL,
                                      CONSTRAINT profile_image_pkey PRIMARY KEY (image_id),
                                      CONSTRAINT fk7499uukxrqn9c6ue4g8uox6ao FOREIGN KEY (profile_id) REFERENCES public.profile(profile_id)
);


-- public.question_answer definition

-- Drop table

-- DROP TABLE public.question_answer;

CREATE TABLE public.question_answer (
                                        answer_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        created_at timestamp(6) NOT NULL,
                                        updated_at timestamp(6) NOT NULL,
                                        answer text NULL,
                                        profile_id int8 NOT NULL,
                                        question_id int8 NOT NULL,
                                        CONSTRAINT question_answer_pkey PRIMARY KEY (answer_id),
                                        CONSTRAINT ukceaeg7ab6u9w7tht8f2lxfvb9 UNIQUE (profile_id, question_id),
                                        CONSTRAINT fk6dicp7lwymw77ry50wa2wrlab FOREIGN KEY (profile_id) REFERENCES public.profile(profile_id),
                                        CONSTRAINT fkpgc6cidvg9xr27j4170epkcaq FOREIGN KEY (question_id) REFERENCES public.questions(question_id)
);


-- public.refresh_tokens definition

-- Drop table

-- DROP TABLE public.refresh_tokens;

CREATE TABLE public.refresh_tokens (
                                       token_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       created_at timestamp(6) NOT NULL,
                                       updated_at timestamp(6) NOT NULL,
                                       expires_at timestamp(6) NOT NULL,
                                       refresh_token varchar(512) NOT NULL,
                                       user_id int8 NOT NULL,
                                       CONSTRAINT refresh_tokens_pkey PRIMARY KEY (token_id),
                                       CONSTRAINT uk1yihy5j142kjit22kgccjixro UNIQUE (refresh_token),
                                       CONSTRAINT uk7tdcd6ab5wsgoudnvj7xf1b7l UNIQUE (user_id),
                                       CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);