-- V2__add_meeting_and_chat.sql
-- 1. Notification (알림) - 로컬에만 있는 기능 추가
CREATE TABLE IF NOT EXISTS public.notification (
                                                   id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   created_at timestamptz(6) NOT NULL,
    is_read bool NOT NULL,
    "type" int2 NULL CHECK (((type >= 0) AND (type <= 5))),
    user_id int8 NULL,
    "data" text NULL,
    message varchar(255) NULL,
    title varchar(255) NULL
    );
-- 1. [필수] Meeting 테이블이 참조하는 Regions 테이블 생성 (운영에 없다면 생성)
CREATE TABLE IF NOT EXISTS public.regions (
    sigungu_code varchar(5) NOT NULL,
    sido_code varchar(2) NOT NULL,
    sido_name varchar(255) NULL,
    sigungu_name varchar(255) NULL,
    CONSTRAINT regions_pkey PRIMARY KEY (sigungu_code)
    );

-- 2. Meeting(미팅) 도메인 테이블 생성
CREATE TABLE public.meeting (
                                id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                created_at timestamptz(6) NOT NULL,
                                updated_at timestamptz(6) NOT NULL,
                                code varchar(255) NOT NULL,
                                room_name varchar(255) NULL,
                                meeting_status int2 NULL,

    -- 인원 및 나이 제한
                                max_members int4 NULL,
                                current_members int4 NULL,
                                min_age int4 NULL,
                                max_age int4 NULL,
                                avg_age float8 NOT NULL,
                                gender int2 NULL,

    -- 매칭 관련
                                occupancy_score int4 NULL,
                                remaining_reject_count int4 NULL,
                                matching_start_at timestamptz(6) NULL,

    -- 외래키 컬럼
                                created_by int8 NOT NULL,
                                sigungu_code varchar(5) NULL,

                                CONSTRAINT meeting_code_key UNIQUE (code),
                                CONSTRAINT fk_meeting_creator FOREIGN KEY (created_by) REFERENCES public.users(user_id),
                                CONSTRAINT fk_meeting_region FOREIGN KEY (sigungu_code) REFERENCES public.regions(sigungu_code)
);

CREATE TABLE public.meeting_members (
                                        id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        joined_at timestamptz(6) NOT NULL,
                                        meeting_role int2 NULL,
                                        status int2 NULL,
                                        meeting_id int8 NULL,
                                        user_id int8 NULL,
                                        CONSTRAINT fk_meeting_members_meeting FOREIGN KEY (meeting_id) REFERENCES public.meeting(id),
                                        CONSTRAINT fk_meeting_members_user FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);

CREATE TABLE public.meeting_matches (
                                        id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        created_at timestamptz(6) NOT NULL,
                                        decision_dead_line timestamptz(6) NULL,
                                        matching_status int2 NULL,
                                        meeting1decision int2 NULL,
                                        meeting2decision int2 NULL,
                                        meeting1_id int8 NOT NULL,
                                        meeting2_id int8 NOT NULL,
                                        CONSTRAINT fk_match_meeting1 FOREIGN KEY (meeting1_id) REFERENCES public.meeting(id),
                                        CONSTRAINT fk_match_meeting2 FOREIGN KEY (meeting2_id) REFERENCES public.meeting(id)
);

-- 3. Chat(채팅) 도메인 테이블 생성
CREATE TABLE public.chat_rooms (
                                   id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   created_at timestamptz(6) NOT NULL,
                                   updated_at timestamptz(6) NOT NULL,
                                   chat_status int2 NULL CHECK (chat_status >= 0 AND chat_status <= 1),
                                   "type" int2 NULL,
                                   match_id int8 NULL UNIQUE,
                                   meeting_id int8 NULL UNIQUE,
                                   CONSTRAINT fk_chat_match FOREIGN KEY (match_id) REFERENCES public.meeting_matches(id),
                                   CONSTRAINT fk_chat_meeting FOREIGN KEY (meeting_id) REFERENCES public.meeting(id)
);

CREATE TABLE public.chat_members (
                                     id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     joined_at timestamptz(6) NULL,
                                     last_read_message_id int4 NULL,
                                     room_id int8 NOT NULL,
                                     user_id int8 NOT NULL,
                                     CONSTRAINT fk_chat_members_room FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id),
                                     CONSTRAINT fk_chat_members_user FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);

CREATE TABLE public.chat_messages (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      created_at timestamptz(6) NOT NULL,
                                      updated_at timestamptz(6) NOT NULL,
                                      "content" varchar(255) NULL,
                                      "type" int2 NULL,
                                      room_id int8 NULL,
                                      sender_user_id int8 NULL,
                                      CONSTRAINT fk_chat_msg_room FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id),
                                      CONSTRAINT fk_chat_msg_user FOREIGN KEY (sender_user_id) REFERENCES public.users(user_id)
);

-- 4. Profile 테이블 구조 변경 (로컬 코드와 맞추기 위함)
-- 로컬에서는 university_id, region_id(sigungu_code) FK를 사용하는 것으로 보임
-- 운영에 있는 기존 데이터(varchar)를 보존하면서 컬럼을 추가함

ALTER TABLE public.profile ADD COLUMN IF NOT EXISTS university_id int8;
ALTER TABLE public.profile ADD COLUMN IF NOT EXISTS region_id varchar(5);

-- FK 연결 (데이터가 NULL이어도 제약조건 생성 가능)
ALTER TABLE public.profile
    ADD CONSTRAINT fk_profile_university FOREIGN KEY (university_id) REFERENCES public.university(university_id);

ALTER TABLE public.profile
    ADD CONSTRAINT fk_profile_region FOREIGN KEY (region_id) REFERENCES public.regions(sigungu_code);

