-- like_request 테이블 생성
CREATE TABLE like_request (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              from_user_id BIGINT NOT NULL,
                              to_user_id BIGINT NOT NULL,
                              status VARCHAR(255) NOT NULL,
                              created_at TIMESTAMP NOT NULL,
                              responded_at TIMESTAMP,
                              PRIMARY KEY (id)
);

-- 유니크 제약조건 추가 (같은 사람에게 중복 요청 방지)
ALTER TABLE like_request
    ADD CONSTRAINT uk_like_from_to
        UNIQUE (from_user_id, to_user_id);

-- 인덱스 생성 (조회 성능 최적화)
CREATE INDEX idx_like_to_status ON like_request (to_user_id, status);
CREATE INDEX idx_like_from_status ON like_request (from_user_id, status);



-- message_request 테이블 생성
CREATE TABLE message_request (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                 from_user_id BIGINT NOT NULL,
                                 to_user_id BIGINT NOT NULL,
                                 message VARCHAR(200),
                                 status VARCHAR(255) NOT NULL,
                                 created_at TIMESTAMP NOT NULL,
                                 responded_at TIMESTAMP,
                                 PRIMARY KEY (id)
);

-- 유니크 제약조건 추가 (같은 사람에게 중복 메시지 요청 방지)
ALTER TABLE message_request
    ADD CONSTRAINT uk_msg_from_to
        UNIQUE (from_user_id, to_user_id);

-- 인덱스 생성 (조회 성능 최적화)
CREATE INDEX idx_msgreq_to_status ON message_request (to_user_id, status);
CREATE INDEX idx_msgreq_from_status ON message_request (from_user_id, status);



-- profile_extra_photo_unlock 테이블 생성
CREATE TABLE profile_extra_photo_unlock (
                                            unlock_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                            requester_user_id BIGINT NOT NULL,
                                            target_user_id BIGINT NOT NULL,
                                            photo_id BIGINT NOT NULL,
                                            created_at TIMESTAMP,
                                            updated_at TIMESTAMP,
                                            PRIMARY KEY (unlock_id)
);

-- 유니크 제약조건 추가 (중복 해제 방지)
ALTER TABLE profile_extra_photo_unlock
ADD CONSTRAINT uk_unlock_requester_target_photo
UNIQUE (requester_user_id, target_user_id, photo_id);


-- profile_rating 테이블 생성
CREATE TABLE profile_rating (
                                profile_rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                from_user_id BIGINT NOT NULL,
                                target_user_id BIGINT NOT NULL,
                                score INTEGER NOT NULL,
                                created_at TIMESTAMP,
                                updated_at TIMESTAMP,
                                PRIMARY KEY (profile_rating_id)
);

-- 유니크 제약조건 추가 (한 사람이 동일 대상을 중복 평가 불가)
ALTER TABLE profile_rating
ADD CONSTRAINT uk_profile_rating_from_to
UNIQUE (from_user_id, target_user_id);
