CREATE TABLE IF NOT EXISTS profile_score_view_unlock (
    unlock_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    requester_user_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (unlock_id)
);

ALTER TABLE profile_score_view_unlock
ADD CONSTRAINT uk_score_view_requester_target
UNIQUE (requester_user_id, target_user_id);
