package mannabom_server.manabom.domain.admin.enums;

public enum AdminAuditActionType {
    ADMIN_LOGIN,
    ADMIN_LOGOUT,
    ADMIN_REFRESH,
    ADMIN_ACCOUNT_CREATE,
    ADMIN_ACCOUNT_UPDATE,
    ADMIN_ACCOUNT_DELETE,
    ADMIN_PASSWORD_RESET,
    USER_STATUS_UPDATE,
    WALLET_ADJUST,
    MEMBERSHIP_ACTIVATE,
    POLICY_UPDATE,
    PUSH_SEND,
    REPORT_PROCESS
}
