plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'mannabom-server'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'		// JPA/Hibernate
	implementation 'org.springframework.boot:spring-boot-starter-security'		// Spring Security
	implementation 'org.springframework.boot:spring-boot-starter-web'			// REST API
	implementation 'org.springframework.boot:spring-boot-starter-validation'	// 입력값 검증
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'	// Redis 연동
	implementation 'org.springframework.boot:spring-boot-starter-webflux'		// 카카오 API 호출용
	implementation 'org.springframework.boot:spring-boot-starter-mail'  		// 이메일 SMTP

	// JWT 토큰 처리
	implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
	implementation 'io.jsonwebtoken:jjwt-impl:0.12.3'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.12.3'

	// 파일 업로드 처리 (로컬 개발용)
	implementation 'commons-io:commons-io:2.11.0'

	// 파일 업로드 처리: AWS S3 SDK v2 (AWS S3 배포용)
	implementation 'software.amazon.awssdk:s3:2.20.26'
	implementation 'software.amazon.awssdk:auth:2.20.26'
	implementation 'software.amazon.awssdk:regions:2.20.26'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// DB
	runtimeOnly 'org.postgresql:postgresql'

    // fcm
    implementation 'com.google.firebase:firebase-admin:9.2.0'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'


	// QueryDSL 설정
	implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
	annotationProcessor "com.querydsl:querydsl-apt:5.0.0:jakarta"
	annotationProcessor "jakarta.annotation:jakarta.annotation-api"
	annotationProcessor "jakarta.persistence:jakarta.persistence-api"

	//매칭 시간 만료를 위한 redisson
	implementation 'org.redisson:redisson-spring-boot-starter:3.26.0'

	//db 형상관리 flyway
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'


}

tasks.named('test') {
	useJUnitPlatform()
}
