package mannabom_server.manabom.domain.meeting.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum SseEventName {
    CONNECTED("CONNECTED"),
    MATCHING_STATUS("MATCHING_STATUS"),
    MATCH_FOUND("MATCH_FOUND"),
    MATCHING_FAILED("MATCHING_FAILED"),
    DECISION_RESULT("DECISION_RESULT"),
    MATCHING_COMPLETED("MATCHING_COMPLETED"),
    NEW_CHAT_MESSAGE("NEW_CHAT_MESSAGE"),
    PHOTO_REQUEST_RECEIVED("PHOTO_REQUEST_RECEIVED"),
    PHOTO_REQUEST_ACCEPTED("PHOTO_REQUEST_ACCEPTED"),
    PHOTO_REQUEST_REJECTED("PHOTO_REQUEST_REJECTED"),
    GIFTICON_DELIVERY_FAILED("GIFTICON_DELIVERY_FAILED");


    private final String description;
}
